security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AMH\MyBlogBundle\Entity\User\User:
         algorithm: bcrypt
         cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
         entity: { class: AMHMyBlogBundle:User\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                username_parameter: "user_login[email]"
                password_parameter: "user_login[password]"
            logout:
                path:  logout
                target: /
            anonymous: ~
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~
                remember_me_parameter: "user_login[remember_me]"
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
