parameters:
#    amh_my_blog.example.class: AMH\MyBlogBundle\Example

services:
#    amh_my_blog.example:
#        class: %amh_my_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
