parameters:
    amh_my_blog.form.type.user_login.class: AMH\MyBlogBundle\Form\UserLoginType
    amh_my_blog.form.type.user_registration.class: AMH\MyBlogBundle\Form\UserRegistrationType

services:
    amh_my_blog.form.type.user_login:
        class: %amh_my_blog.form.type.user_login.class%
        tags:
         - { name: form.type, alias: user_login }
    amh_my_blog.form.type.user_registration:
        class: %amh_my_blog.form.type.user_registration.class%
        tags:
         - { name: form.type, alias: user_registration }
    amh_my_blog.util.entity_generator:
        class: AMH\MyBlogBundle\Util\EntityGenerator
        arguments: [ '@doctrine.orm.entity_manager' ]
    amh_my_blog.twig.extension:
        class: AMH\MyBlogBundle\Twig\AMHExtension
        calls:
         - [setRouter, ["@router"]]
        tags:
         - { name: twig.extension }
    amh_my_blog.form.type.post_rating:
        class: AMH\MyBlogBundle\Form\PostRatingType
        calls:
         - [setRatingRange, [1,5]]
        tags:
         - { name: form.type, alias: post_rating }
    amh_my_blog.default.controller:
        class: AMH\MyBlogBUndle\Controller\DefaultController
        tags:
         - { name: security.scure_service }
    amh_my_blog.form.type.post:
        class: AMH\MyBlogBundle\Form\PostType
        tags:
         - { name: form.type, alias: post_add }
    amh_my_blog_cache_factory:
        class: AMH\MyBlogBundle\Util\CacheFactory
    amh_my_blog_cache:
        class: Memcache
        factory_service: amh_my_blog_cache_factory
        factory_method: createMemcached
    amh_my_blog_doctrine_cache:
        class: Doctrine\Common\Cache\Cache
        factory_service: amh_my_blog_cache_factory
        factory_method: createDoctrineCache
        arguments: [ "@amh_my_blog_cache" ]

    amh_my_blog.geo_detector:
        class: AMH\MyBlogBundle\Util\GeoDetector
        
    kernel.listener.geo_subdomain_listener:
            class: AMH\MyBlogBundle\Event\GeoSubdomainEventListener
            arguments:
                - "@amh_my_blog.geo_detector"
                - "@router"
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    amh_my_blog.post_repository:
        class: AMH\MyBlogBundle\Entity\Blog\PostRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AMH\MyBlogBundle\Entity\Blog\Post

    amh_my_blog.reward_double_rates:
        class: AMH\MyBlogBundle\Reward\DoubleRatesReward
        arguments:
            - "@amh_my_blog.post_repository"

    amh_my_blog.reward_increment_views:
        class: AMH\MyBlogBundle\Reward\IncrementViewsReward
        arguments:
            - "@amh_my_blog.post_repository"

    amh_my_blog.reward_delegate:
        class: AMH\MyBlogBundle\Reward\RewardDelegate
        arguments:
            - ["@amh_my_blog.reward_double_rates", "@amh_my_blog.reward_increment_views"]

    amh_my_blog.milstone_listener:
        class: AMH\MyBlogBundle\Event\MilestoneEventListener
        arguments:
            - "@amh_my_blog.reward_delegate"
        tags:
            - { name: kernel.event_listener, event: amh_my_blog.milestone_achieved, method: onMilestoneAchieved }