parameters:
    amh_my_blog.form.type.user_login.class: AMH\MyBlogBundle\Form\UserLoginType
    amh_my_blog.form.type.user_registration.class: AMH\MyBlogBundle\Form\UserRegistrationType

services:
    amh_my_blog.form.type.user_login:
        class: %amh_my_blog.form.type.user_login.class%
        tags:
         - { name: form.type, alias: user_login }
    amh_my_blog.form.type.user_registration:
        class: %amh_my_blog.form.type.user_registration.class%
        tags:
         - { name: form.type, alias: user_registration }
    amh_my_blog.util.entity_generator:
        class: AMH\MyBlogBundle\Util\EntityGenerator
        arguments: [ '@doctrine.orm.entity_manager' ]
    amh_my_blog.twig.extension:
        class: AMH\MyBlogBundle\Twig\AMHExtension
        calls:
         - [setRouter, ["@router"]]
        tags:
         - { name: twig.extension }
