AMH\MyBlogBundle\Entity\User\User:
 group_sequence:
  - User
  - login
  - registration
 properties:
  email:
   - Email: { groups: [login] }
   - NotBlank: { groups: [login] }
   - Length: { max: 100, groups: [login] }
  password:
   - NotBlank: { groups: [login] }
   - Length: { min: 5, max: 100, groups: [login] }
  name:
   - NotBlank: { groups: [registration] }
   - Length: { min: 3, max: 100, groups: [registration] }
   - Regex: { pattern: "/^[a-z]+[\w\s]*?$/i", groups: [registration] }
AMH\MyBlogBundle\Entity\Blog\Post:
 properties:
  title:
   - NotBlank: ~
   - Regex: { pattern: "/^[a-z]+[\w\s]*?$/i" }
   - Length: { min: 5, max: 60 }
  text:
   - NotBlank: ~
   - Length: { min: 10, max: 2000 }
